version: '3.8'

services:
  postgres:
    container_name: crud-with-login
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: crud-with-login
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres